### ISSUE TITLE
I think there is No Multi threading. My system hung because of this game

### ISSUE THREAD

**Issue by theunhackable** [SoftbearStudios/mk48#194]
**Describe your feature request**

**Additional context**

**Comment by finnbear** [comment]
Hi there,

I can't tell if you are referring to playing the game, or hosting your own game server.

It should not be possible for the game _client_ to hang your entire system, because it is sandboxed by your web browser. It it did hang your system, that would involve a browser bug. Even so, if this ever happens again, we would be interested to see a copy/screenshot of the Inspect Element Console. As for multi-threading, the game client would barely benefit from it and it is barely possible in browser-based games.

<details>
<summary>If you are referring to hosting your own game server...</summary>
...the server does have multithreading which can be enabled by changing this line https://github.com/SoftbearStudios/mk48/blob/0b7ba2d3b2b8193f041332d267a2375993e6045e/engine/game_server/Cargo.toml#L40 to have `features = ["rayon"]` instead of `features = []`.
</details>
